# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Oscar\UIS\Instrumentación\laika\Oscuro_grafica.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1288, 475)
        Form.setStyleSheet("background-color: rgb(31, 31, 47);")
        self.Titlle_14 = QtWidgets.QLabel(Form)
        self.Titlle_14.setGeometry(QtCore.QRect(180, 20, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_14.setFont(font)
        self.Titlle_14.setStyleSheet("color:white;\n"
"background-color: transparent;\n"
"\n"
"")
        self.Titlle_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_14.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_14.setObjectName("Titlle_14")
        self.LIVE_13 = QtWidgets.QLabel(Form)
        self.LIVE_13.setGeometry(QtCore.QRect(50, 20, 81, 71))
        self.LIVE_13.setAutoFillBackground(False)
        self.LIVE_13.setStyleSheet("color:black;\n"
"image: url(:/source/layca2.png);\n"
"background-color: rgb(38, 42, 60);\n"
"border-radius: 10px;\n"
"")
        self.LIVE_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LIVE_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIVE_13.setText("")
        self.LIVE_13.setScaledContents(True)
        self.LIVE_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LIVE_13.setObjectName("LIVE_13")
        self.LIVE_12 = QtWidgets.QLabel(Form)
        self.LIVE_12.setGeometry(QtCore.QRect(640, 120, 271, 151))
        self.LIVE_12.setAutoFillBackground(False)
        self.LIVE_12.setStyleSheet("color:black;\n"
"background-color: rgb(38, 42, 60);\n"
"border-radius: 10px;\n"
"")
        self.LIVE_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LIVE_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIVE_12.setText("")
        self.LIVE_12.setScaledContents(True)
        self.LIVE_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LIVE_12.setObjectName("LIVE_12")
        self.Titlle_16 = QtWidgets.QLabel(Form)
        self.Titlle_16.setGeometry(QtCore.QRect(680, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_16.setFont(font)
        self.Titlle_16.setStyleSheet("color:white;\n"
"background-color: transparent")
        self.Titlle_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_16.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_16.setObjectName("Titlle_16")
        self.Titlle_39 = QtWidgets.QLabel(Form)
        self.Titlle_39.setGeometry(QtCore.QRect(380, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_39.setFont(font)
        self.Titlle_39.setStyleSheet("color:white;\n"
"background-color: transparent")
        self.Titlle_39.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_39.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_39.setObjectName("Titlle_39")
        self.LIVE_140 = QtWidgets.QLabel(Form)
        self.LIVE_140.setGeometry(QtCore.QRect(330, 120, 271, 151))
        self.LIVE_140.setAutoFillBackground(False)
        self.LIVE_140.setStyleSheet("color:black;\n"
"background-color: rgb(38, 42, 60);\n"
"border-radius: 10px;\n"
"")
        self.LIVE_140.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LIVE_140.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIVE_140.setText("")
        self.LIVE_140.setScaledContents(True)
        self.LIVE_140.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LIVE_140.setObjectName("LIVE_140")
        self.Titlle_53 = QtWidgets.QLabel(Form)
        self.Titlle_53.setGeometry(QtCore.QRect(80, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_53.setFont(font)
        self.Titlle_53.setStyleSheet("color:white;\n"
"background-color: transparent")
        self.Titlle_53.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_53.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_53.setObjectName("Titlle_53")
        self.LIVE_15 = QtWidgets.QLabel(Form)
        self.LIVE_15.setGeometry(QtCore.QRect(30, 120, 271, 151))
        self.LIVE_15.setAutoFillBackground(False)
        self.LIVE_15.setStyleSheet("color:black;\n"
"background-color: rgb(38, 42, 60);\n"
"border-radius: 10px;\n"
"")
        self.LIVE_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LIVE_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIVE_15.setText("")
        self.LIVE_15.setScaledContents(True)
        self.LIVE_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LIVE_15.setObjectName("LIVE_15")
        self.LIVE_16 = QtWidgets.QLabel(Form)
        self.LIVE_16.setGeometry(QtCore.QRect(30, 300, 271, 151))
        self.LIVE_16.setAutoFillBackground(False)
        self.LIVE_16.setStyleSheet("color:black;\n"
"background-color: rgb(38, 42, 60);\n"
"border-radius: 10px;\n"
"")
        self.LIVE_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LIVE_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIVE_16.setText("")
        self.LIVE_16.setScaledContents(True)
        self.LIVE_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LIVE_16.setObjectName("LIVE_16")
        self.Titlle_83 = QtWidgets.QLabel(Form)
        self.Titlle_83.setGeometry(QtCore.QRect(80, 300, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_83.setFont(font)
        self.Titlle_83.setStyleSheet("color:white;\n"
"background-color: transparent")
        self.Titlle_83.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_83.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_83.setObjectName("Titlle_83")
        self.LIVE_17 = QtWidgets.QLabel(Form)
        self.LIVE_17.setGeometry(QtCore.QRect(330, 300, 271, 151))
        self.LIVE_17.setAutoFillBackground(False)
        self.LIVE_17.setStyleSheet("color:black;\n"
"background-color: rgb(38, 42, 60);\n"
"border-radius: 10px;\n"
"")
        self.LIVE_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LIVE_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIVE_17.setText("")
        self.LIVE_17.setScaledContents(True)
        self.LIVE_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LIVE_17.setObjectName("LIVE_17")
        self.Titlle_94 = QtWidgets.QLabel(Form)
        self.Titlle_94.setGeometry(QtCore.QRect(380, 300, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_94.setFont(font)
        self.Titlle_94.setStyleSheet("color:white;\n"
"background-color: transparent")
        self.Titlle_94.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_94.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_94.setObjectName("Titlle_94")
        self.Titlle_112 = QtWidgets.QLabel(Form)
        self.Titlle_112.setGeometry(QtCore.QRect(680, 300, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_112.setFont(font)
        self.Titlle_112.setStyleSheet("color:white;\n"
"background-color: transparent")
        self.Titlle_112.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_112.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_112.setObjectName("Titlle_112")
        self.LIVE_19 = QtWidgets.QLabel(Form)
        self.LIVE_19.setGeometry(QtCore.QRect(930, 120, 331, 331))
        self.LIVE_19.setAutoFillBackground(False)
        self.LIVE_19.setStyleSheet("color:black;\n"
"image: url(:/source/sources/layca_image.jpg);\n"
"background-color: rgb(38, 42, 60);\n"
"border-radius: 10px;\n"
"")
        self.LIVE_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LIVE_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIVE_19.setText("")
        self.LIVE_19.setScaledContents(True)
        self.LIVE_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LIVE_19.setObjectName("LIVE_19")
        self.LIVE_20 = QtWidgets.QLabel(Form)
        self.LIVE_20.setGeometry(QtCore.QRect(10, 20, 1231, 71))
        self.LIVE_20.setAutoFillBackground(False)
        self.LIVE_20.setStyleSheet("color:black;\n"
"background-color: rgb(38, 42, 60);\n"
"border-radius: 10px;\n"
"")
        self.LIVE_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LIVE_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIVE_20.setText("")
        self.LIVE_20.setScaledContents(True)
        self.LIVE_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LIVE_20.setObjectName("LIVE_20")
        self.LIVE_21 = QtWidgets.QLabel(Form)
        self.LIVE_21.setGeometry(QtCore.QRect(30, 20, 141, 71))
        self.LIVE_21.setAutoFillBackground(False)
        self.LIVE_21.setStyleSheet("color:black;\n"
"background-color: rgb(38, 42, 60);\n"
"image: url(:/source/sources/logo_azul5.png);\n"
"border-radius: 10px;\n"
"")
        self.LIVE_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LIVE_21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIVE_21.setText("")
        self.LIVE_21.setScaledContents(True)
        self.LIVE_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LIVE_21.setObjectName("LIVE_21")
        self.Titlle_124 = QtWidgets.QLabel(Form)
        self.Titlle_124.setGeometry(QtCore.QRect(380, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_124.setFont(font)
        self.Titlle_124.setStyleSheet("color:white;\n"
"background-color: transparent")
        self.Titlle_124.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_124.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_124.setObjectName("Titlle_124")
        self.Titlle_125 = QtWidgets.QLabel(Form)
        self.Titlle_125.setGeometry(QtCore.QRect(370, 50, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_125.setFont(font)
        self.Titlle_125.setStyleSheet("color:white;\n"
"background-color: transparent")
        self.Titlle_125.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_125.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_125.setObjectName("Titlle_125")
        self.Titlle_126 = QtWidgets.QLabel(Form)
        self.Titlle_126.setGeometry(QtCore.QRect(690, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_126.setFont(font)
        self.Titlle_126.setStyleSheet("color:white;\n"
"background-color: transparent")
        self.Titlle_126.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_126.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_126.setObjectName("Titlle_126")
        self.Titlle_127 = QtWidgets.QLabel(Form)
        self.Titlle_127.setGeometry(QtCore.QRect(940, 50, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_127.setFont(font)
        self.Titlle_127.setStyleSheet("color:white;\n"
"background-color: transparent")
        self.Titlle_127.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_127.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_127.setObjectName("Titlle_127")
        self.Titlle_128 = QtWidgets.QLabel(Form)
        self.Titlle_128.setGeometry(QtCore.QRect(980, 20, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_128.setFont(font)
        self.Titlle_128.setStyleSheet("color:white;\n"
"background-color: transparent")
        self.Titlle_128.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_128.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_128.setObjectName("Titlle_128")
        self.Titlle_129 = QtWidgets.QLabel(Form)
        self.Titlle_129.setGeometry(QtCore.QRect(670, 50, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_129.setFont(font)
        self.Titlle_129.setStyleSheet("color:white;\n"
"background-color: transparent")
        self.Titlle_129.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_129.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_129.setObjectName("Titlle_129")
        self.Titlle_173 = QtWidgets.QLabel(Form)
        self.Titlle_173.setGeometry(QtCore.QRect(190, 135, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_173.setFont(font)
        self.Titlle_173.setStyleSheet("color:white;\n"
"image: url(:/source/icons8-info-128 (2).png);\n"
"background-color: transparent;\n"
"\n"
"")
        self.Titlle_173.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_173.setText("")
        self.Titlle_173.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_173.setObjectName("Titlle_173")
        self.Titlle_174 = QtWidgets.QLabel(Form)
        self.Titlle_174.setGeometry(QtCore.QRect(520, 137, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_174.setFont(font)
        self.Titlle_174.setStyleSheet("color:white;\n"
"image: url(:/source/icons8-info-128 (2).png);\n"
"background-color: transparent;\n"
"\n"
"")
        self.Titlle_174.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_174.setText("")
        self.Titlle_174.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_174.setObjectName("Titlle_174")
        self.Titlle_175 = QtWidgets.QLabel(Form)
        self.Titlle_175.setGeometry(QtCore.QRect(805, 137, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_175.setFont(font)
        self.Titlle_175.setStyleSheet("color:white;\n"
"image: url(:/source/icons8-info-128 (2).png);\n"
"background-color: transparent;\n"
"\n"
"")
        self.Titlle_175.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_175.setText("")
        self.Titlle_175.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_175.setObjectName("Titlle_175")
        self.Titlle_176 = QtWidgets.QLabel(Form)
        self.Titlle_176.setGeometry(QtCore.QRect(225, 312, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_176.setFont(font)
        self.Titlle_176.setStyleSheet("color:white;\n"
"image: url(:/source/icons8-info-128 (2).png);\n"
"background-color: transparent;\n"
"\n"
"")
        self.Titlle_176.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_176.setText("")
        self.Titlle_176.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_176.setObjectName("Titlle_176")
        self.Titlle_177 = QtWidgets.QLabel(Form)
        self.Titlle_177.setGeometry(QtCore.QRect(495, 312, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_177.setFont(font)
        self.Titlle_177.setStyleSheet("color:white;\n"
"image: url(:/source/icons8-info-128 (2).png);\n"
"background-color: transparent;\n"
"\n"
"")
        self.Titlle_177.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_177.setText("")
        self.Titlle_177.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_177.setObjectName("Titlle_177")
        self.Titlle_178 = QtWidgets.QLabel(Form)
        self.Titlle_178.setGeometry(QtCore.QRect(770, 310, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_178.setFont(font)
        self.Titlle_178.setStyleSheet("color:white;\n"
"image: url(:/source/icons8-info-128 (2).png);\n"
"background-color: transparent;\n"
"\n"
"")
        self.Titlle_178.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_178.setText("")
        self.Titlle_178.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_178.setObjectName("Titlle_178")
        self.Titlle_179 = QtWidgets.QLabel(Form)
        self.Titlle_179.setGeometry(QtCore.QRect(515, 28, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_179.setFont(font)
        self.Titlle_179.setStyleSheet("color:white;\n"
"image: url(:/source/sources/icons8-ok-144.png);\n"
"background-color: transparent;\n"
"\n"
"")
        self.Titlle_179.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_179.setText("")
        self.Titlle_179.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_179.setObjectName("Titlle_179")
        self.Titlle_180 = QtWidgets.QLabel(Form)
        self.Titlle_180.setGeometry(QtCore.QRect(545, 55, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_180.setFont(font)
        self.Titlle_180.setStyleSheet("color:white;\n"
"image: url(:/source/sources/icons8-ok-144.png);\n"
"background-color: transparent;\n"
"\n"
"")
        self.Titlle_180.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_180.setText("")
        self.Titlle_180.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_180.setObjectName("Titlle_180")
        self.Titlle_181 = QtWidgets.QLabel(Form)
        self.Titlle_181.setGeometry(QtCore.QRect(855, 55, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_181.setFont(font)
        self.Titlle_181.setStyleSheet("color:white;\n"
"image: url(:/source/sources/icons8-ok-144.png);\n"
"background-color: transparent;\n"
"\n"
"")
        self.Titlle_181.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_181.setText("")
        self.Titlle_181.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_181.setObjectName("Titlle_181")
        self.Titlle_183 = QtWidgets.QLabel(Form)
        self.Titlle_183.setGeometry(QtCore.QRect(1165, 28, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_183.setFont(font)
        self.Titlle_183.setStyleSheet("color:white;\n"
"image: url(:/source/sources/icons8-ok-144.png);\n"
"background-color: transparent;\n"
"\n"
"")
        self.Titlle_183.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_183.setText("")
        self.Titlle_183.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_183.setObjectName("Titlle_183")
        self.Titlle_184 = QtWidgets.QLabel(Form)
        self.Titlle_184.setGeometry(QtCore.QRect(1190, 55, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_184.setFont(font)
        self.Titlle_184.setStyleSheet("color:white;\n"
"image: url(:/source/sources/icons8-ok-144.png);\n"
"background-color: transparent;\n"
"\n"
"")
        self.Titlle_184.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_184.setText("")
        self.Titlle_184.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_184.setObjectName("Titlle_184")
        self.Titlle_182 = QtWidgets.QLabel(Form)
        self.Titlle_182.setGeometry(QtCore.QRect(830, 28, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Titlle_182.setFont(font)
        self.Titlle_182.setStyleSheet("color:white;\n"
"image: url(:/source/sources/icons8-ok-144.png);\n"
"background-color: transparent;\n"
"\n"
"")
        self.Titlle_182.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titlle_182.setText("")
        self.Titlle_182.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlle_182.setObjectName("Titlle_182")
        self.LIVE_22 = QtWidgets.QLabel(Form)
        self.LIVE_22.setGeometry(QtCore.QRect(630, 300, 271, 151))
        self.LIVE_22.setAutoFillBackground(False)
        self.LIVE_22.setStyleSheet("color:black;\n"
"background-color: rgb(38, 42, 60);\n"
"border-radius: 10px;\n"
"")
        self.LIVE_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LIVE_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIVE_22.setText("")
        self.LIVE_22.setScaledContents(True)
        self.LIVE_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LIVE_22.setObjectName("LIVE_22")
        self.LIVE_14 = QtWidgets.QLabel(Form)
        self.LIVE_14.setGeometry(QtCore.QRect(320, 140, 291, 131))
        self.LIVE_14.setAutoFillBackground(False)
        self.LIVE_14.setStyleSheet("background-color: transparent;\n"
"border-radius: 10px;\n"
"")
        self.LIVE_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LIVE_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIVE_14.setText("")
        self.LIVE_14.setScaledContents(True)
        self.LIVE_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LIVE_14.setObjectName("LIVE_14")
        self.LIVE_18 = QtWidgets.QLabel(Form)
        self.LIVE_18.setGeometry(QtCore.QRect(640, 140, 271, 131))
        self.LIVE_18.setAutoFillBackground(False)
        self.LIVE_18.setStyleSheet("color:black;\n"
"background-color: rgb(38, 42, 60);\n"
"border-radius: 10px;\n"
"")
        self.LIVE_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LIVE_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIVE_18.setText("")
        self.LIVE_18.setScaledContents(True)
        self.LIVE_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LIVE_18.setObjectName("LIVE_18")
        self.LIVE_23 = QtWidgets.QLabel(Form)
        self.LIVE_23.setGeometry(QtCore.QRect(630, 320, 271, 131))
        self.LIVE_23.setAutoFillBackground(False)
        self.LIVE_23.setStyleSheet("color:black;\n"
"background-color: rgb(38, 42, 60);\n"
"border-radius: 10px;\n"
"")
        self.LIVE_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LIVE_23.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIVE_23.setText("")
        self.LIVE_23.setScaledContents(True)
        self.LIVE_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LIVE_23.setObjectName("LIVE_23")
        self.LIVE_24 = QtWidgets.QLabel(Form)
        self.LIVE_24.setGeometry(QtCore.QRect(330, 320, 271, 131))
        self.LIVE_24.setAutoFillBackground(False)
        self.LIVE_24.setStyleSheet("color:black;\n"
"background-color: rgb(38, 42, 60);\n"
"border-radius: 10px;\n"
"")
        self.LIVE_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LIVE_24.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIVE_24.setText("")
        self.LIVE_24.setScaledContents(True)
        self.LIVE_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LIVE_24.setObjectName("LIVE_24")
        self.LIVE_25 = QtWidgets.QLabel(Form)
        self.LIVE_25.setGeometry(QtCore.QRect(30, 320, 271, 131))
        self.LIVE_25.setAutoFillBackground(False)
        self.LIVE_25.setStyleSheet("color:black;\n"
"background-color: rgb(38, 42, 60);\n"
"border-radius: 10px;\n"
"")
        self.LIVE_25.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LIVE_25.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIVE_25.setText("")
        self.LIVE_25.setScaledContents(True)
        self.LIVE_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LIVE_25.setObjectName("LIVE_25")
        self.LIVE_26 = QtWidgets.QLabel(Form)
        self.LIVE_26.setGeometry(QtCore.QRect(30, 140, 271, 131))
        self.LIVE_26.setAutoFillBackground(False)
        self.LIVE_26.setStyleSheet("color:black;\n"
"background-color: rgb(38, 42, 60);\n"
"border-radius: 10px;\n"
"")
        self.LIVE_26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LIVE_26.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIVE_26.setText("")
        self.LIVE_26.setScaledContents(True)
        self.LIVE_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LIVE_26.setObjectName("LIVE_26")
        self.LIVE_22.raise_()
        self.LIVE_20.raise_()
        self.LIVE_17.raise_()
        self.LIVE_16.raise_()
        self.LIVE_15.raise_()
        self.LIVE_140.raise_()
        self.Titlle_14.raise_()
        self.LIVE_13.raise_()
        self.LIVE_12.raise_()
        self.LIVE_19.raise_()
        self.LIVE_21.raise_()
        self.Titlle_124.raise_()
        self.Titlle_125.raise_()
        self.Titlle_126.raise_()
        self.Titlle_127.raise_()
        self.Titlle_128.raise_()
        self.Titlle_129.raise_()
        self.Titlle_173.raise_()
        self.Titlle_174.raise_()
        self.Titlle_175.raise_()
        self.Titlle_176.raise_()
        self.Titlle_177.raise_()
        self.Titlle_178.raise_()
        self.Titlle_179.raise_()
        self.Titlle_180.raise_()
        self.Titlle_181.raise_()
        self.Titlle_183.raise_()
        self.Titlle_184.raise_()
        self.Titlle_182.raise_()
        self.LIVE_14.raise_()
        self.Titlle_39.raise_()
        self.LIVE_18.raise_()
        self.Titlle_16.raise_()
        self.LIVE_23.raise_()
        self.Titlle_112.raise_()
        self.LIVE_24.raise_()
        self.Titlle_94.raise_()
        self.LIVE_25.raise_()
        self.Titlle_83.raise_()
        self.LIVE_26.raise_()
        self.Titlle_53.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Titlle_14.setText(_translate("Form", "Laika"))
        self.Titlle_16.setText(_translate("Form", "Presion [Kpa]"))
        self.Titlle_39.setText(_translate("Form", "Temperatura [°C]"))
        self.Titlle_53.setText(_translate("Form", "Altitud [m]"))
        self.Titlle_83.setText(_translate("Form", "Aceleración [m²/s]"))
        self.Titlle_94.setText(_translate("Form", "Orientación"))
        self.Titlle_112.setText(_translate("Form", "GPS"))
        self.Titlle_124.setText(_translate("Form", "Altitud: 100 [m]"))
        self.Titlle_125.setText(_translate("Form", "Temperatura: 20 [°C]"))
        self.Titlle_126.setText(_translate("Form", "Presion: 100 [Kpa]"))
        self.Titlle_127.setText(_translate("Form", "Aceleración: [1.2,1.5,-9.8] [m²/s]"))
        self.Titlle_128.setText(_translate("Form", "Orientación: [0,1.2,0.5]"))
        self.Titlle_129.setText(_translate("Form", "GPS [7.12539, -73.1198]"))
import source_rc
